### ISSUE TITLE
Error "tabletojson.convert is not a function" in v2.0.0

### ISSUE THREAD

**Issue by aarongoldenthal** [maugenst/tabletojson#50]
Running legacy code that previously worked with v1.2.0, e.g.

```js
const tabletojson = require('tabletojson');
const result = tabletojson.convert(html);
```

results in `TypeError: tabletojson.convert is not a function`.  It appears in v2.0.0 there is no default export, only the Tabletojson property, so this code must be changed as follows:

```js
const tabletojson = require('tabletojson').Tabletojson;
const result = tabletojson.convert(html);

or

const { Tabletojson } = require('tabletojson');
const result = Tabletojson.convert(html);
```

This does not appear to be intentional as none of the examples were updated.

**Comment by piranna** [comment]
I'm facing the same problem, this is because code now is exporting a class with static methods, probably due to usage of Typescript. It should be exporting just only the methods. Typescript building is failling to me too.

**Comment by maugenst** [comment]
I'm currently working on a fix for this issue.

**Comment by piranna** [comment]
> I'm currently working on a fix for this issue.

Cool! :-D I have been reviewing and fixing some linting issues, I'm going to create a pull-request right now :-)

**Comment by maugenst** [comment]
I've just created a mock since the spawned express server doesn't work in travis :-(

**Comment by piranna** [comment]
You have the pull-request at https://github.com/maugenst/tabletojson/pull/51 :-)

**Comment by maugenst** [comment]
I changed the README.md to reflect the new api import.

**Comment by piranna** [comment]
> I changed the README.md to reflect the new api import.

Good thing, thanks :-)
